{{- if and .Values.worker.enabled .Values.prometheus.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "audiobook-studio.fullname" . }}-worker
  labels:
    {{- include "audiobook-studio.labels" . | nindent 4 }}
    component: worker
    release: prometheus
spec:
  selector:
    matchLabels:
      {{- include "audiobook-studio.selectorLabels" . | nindent 6 }}
      component: worker
  endpoints:
    - port: metrics
      interval: {{ .Values.prometheus.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.prometheus.serviceMonitor.scrapeTimeout }}
      path: /metrics
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
{{- end }}
