"""Garbage Collection Manager for Audiobook Studio.

Manages automatic cleanup of temporary segment files after successful book export.
Supports configurable retention policies via environment variables.
"""

from __future__ import annotations

import logging
import os
import shutil
from dataclasses import dataclass, field
from datetime import datetime, timedelta
from pathlib import Path
from typing import Dict, List, Optional

logger = logging.getLogger(__name__)


# Final export file extensions (should never be deleted if keep_final=True)
FINAL_EXPORT_SUFFIXES = {".m4b", ".srt", ".vtt", ".zip", ".m4a"}

# Typical segment file naming patterns
SEGMENT_PATTERNS = ("segment_", "book_ch", "ch_", "_p", "retry")


@dataclass
class GCRetentionPolicy:
    """Retention policy for garbage collection.

    Configured via environment variables:
    - GC_POLICY: "clean_on_success" | "keep_for_days" | "keep_all" (default: "clean_on_success")
    - GC_KEEP_DAYS: Days to keep segments if policy is "keep_for_days" (default: 7)
    - GC_KEEP_FINAL: Whether to keep the final exported output (default: true)
    - GC_MAX_AGE_DAYS: Maximum age of any segment file before forced cleanup (default: 30)
    """

    policy: str = field(default_factory=lambda: os.getenv("GC_POLICY", "clean_on_success"))
    keep_days: int = field(default_factory=lambda: int(os.getenv("GC_KEEP_DAYS", "7")))
    keep_final: bool = field(default_factory=lambda: os.getenv("GC_KEEP_FINAL", "true").lower() == "true")
    max_age_days: int = field(default_factory=lambda: int(os.getenv("GC_MAX_AGE_DAYS", "30")))

    def __post_init__(self):
        valid_policies = {"clean_on_success", "keep_for_days", "keep_all"}
        if self.policy not in valid_policies:
            logger.warning(f"Invalid GC_POLICY '{self.policy}', defaulting to 'clean_on_success'")
            self.policy = "clean_on_success"


@dataclass
class GCResult:
    """Result of a garbage collection operation."""

    project_id: int
    deleted_files: List[str] = field(default_factory=list)
    freed_bytes: int = 0
    errors: List[str] = field(default_factory=list)
    policy_applied: str = ""
    timestamp: str = field(default_factory=lambda: datetime.now().isoformat())

    @property
    def freed_mb(self) -> float:
        return self.freed_bytes / (1024 * 1024)


class GCManager:
    """Garbage Collection Manager for cleaning up temporary audio segments.

    Segments are generated by the synthesis pipeline in:
    - Pipeline output dir: ./output/project_{id}/ (segments + final exports mixed)
    - Storage: ./storage/books/{project_id}/audio/ (permanent segment storage)

    Final exports (M4B, SRT, VTT, ZIP, M4A) are kept by default.
    Segment files (WAV, MP3 with segment naming patterns) are cleaned based on policy.
    """

    def __init__(
        self,
        pipeline_output_dir: str = "./output",
        storage_root: str = "./storage/books",
        policy: Optional[GCRetentionPolicy] = None,
    ):
        self.pipeline_output_dir = Path(pipeline_output_dir)
        self.storage_root = Path(storage_root)
        self.policy = policy or GCRetentionPolicy()

    def _get_project_dirs(self, project_id: int) -> List[Path]:
        """Get all directories that may contain segment/export files for a project."""
        dirs = []

        # Main project output directory (contains both segments and final exports)
        project_output = self.pipeline_output_dir / f"project_{project_id}"
        if project_output.exists():
            dirs.append(project_output)

        # Storage audio directory
        storage_audio = self.storage_root / str(project_id) / "audio"
        if storage_audio.exists():
            dirs.append(storage_audio)

        return dirs

    def _is_final_export(self, path: Path) -> bool:
        """Check if a file is a final export product (M4B, SRT, etc.)."""
        return path.suffix.lower() in FINAL_EXPORT_SUFFIXES

    def _is_segment_file(self, path: Path) -> bool:
        """Check if a file is a temporary segment (not a final export)."""
        # Audio file?
        if path.suffix.lower() not in {".wav", ".mp3", ".m4a", ".flac", ".ogg"}:
            return False

        # Final exports have these suffixes
        if self._is_final_export(path):
            return False

        # Check for segment naming patterns
        name = path.name.lower()
        for pattern in SEGMENT_PATTERNS:
            if pattern in name:
                return True

        # Also treat any audio file in project_N dir that's not a final export as segment
        # (conservative: if it looks like an export, keep it)
        if "project_" in name:
            return False

        return True

    def _should_delete_file(self, path: Path, project_id: int, now: datetime, keep_final: bool) -> bool:
        """Determine if a file should be deleted based on policy."""
        if not path.exists() or path.is_dir():
            return False

        is_final = self._is_final_export(path)

        # Never delete final exports if keep_final is True
        if keep_final and is_final:
            return False

        # Check max age (forced cleanup regardless of policy)
        try:
            mtime = datetime.fromtimestamp(path.stat().st_mtime)
            if (now - mtime).days > self.policy.max_age_days:
                return True
        except OSError:
            return False

        # Policy-based decision
        if self.policy.policy == "keep_all":
            return False
        elif self.policy.policy == "keep_for_days":
            try:
                mtime = datetime.fromtimestamp(path.stat().st_mtime)
                if (now - mtime).days < self.policy.keep_days:
                    return False
            except OSError:
                pass
            return True
        elif self.policy.policy == "clean_on_success":
            # Delete segment files; delete final exports only if keep_final=False
            if is_final:
                return not keep_final
            return self._is_segment_file(path)

        return False

    def cleanup_project_segments(
        self,
        project_id: int,
        keep_final: Optional[bool] = None,
        dry_run: bool = False,
    ) -> GCResult:
        """Clean up temporary segment files for a project after export.

        Args:
            project_id: Project ID to clean up
            keep_final: Override policy's keep_final setting
            dry_run: If True, only report what would be deleted

        Returns:
            GCResult with details of cleanup operation
        """
        result = GCResult(project_id=project_id, policy_applied=self.policy.policy)
        keep_final = keep_final if keep_final is not None else self.policy.keep_final

        dirs = self._get_project_dirs(project_id)
        now = datetime.now()

        for dir_path in dirs:
            if not dir_path.exists():
                continue

            for file_path in dir_path.rglob("*"):
                if not file_path.is_file():
                    continue

                if self._should_delete_file(file_path, project_id, now, keep_final):
                    try:
                        size = file_path.stat().st_size
                        if not dry_run:
                            file_path.unlink()
                            logger.info(f"GC deleted segment: {file_path} ({size} bytes)")
                        result.deleted_files.append(str(file_path))
                        result.freed_bytes += size
                    except OSError as e:
                        err = f"Failed to delete {file_path}: {e}"
                        result.errors.append(err)
                        logger.warning(err)

        # Clean up empty directories (except the main project directory if it has exports)
        if not dry_run:
            for dir_path in dirs:
                try:
                    self._remove_empty_dirs(dir_path, is_main_project_dir=(dir_path.name == f"project_{project_id}"))
                except OSError:
                    pass

        logger.info(
            f"GC completed for project {project_id}: "
            f"deleted {len(result.deleted_files)} files, "
            f"freed {result.freed_mb:.2f} MB"
        )
        return result

    def _remove_empty_dirs(self, root: Path, is_main_project_dir: bool = False) -> None:
        """Recursively remove empty directories, preserving main project dir."""
        for dirpath in sorted(root.rglob("*"), key=lambda p: len(p.parts), reverse=True):
            if not dirpath.is_dir() or not self._is_empty_dir(dirpath):
                continue
            if is_main_project_dir and dirpath == root:
                continue  # Keep main project directory
            try:
                dirpath.rmdir()
                logger.debug(f"GC removed empty dir: {dirpath}")
            except OSError:
                pass

    def _is_empty_dir(self, path: Path) -> bool:
        """Check if directory is empty (or only contains empty subdirs)."""
        try:
            return not any(path.iterdir())
        except OSError:
            return False

    def sweep_all_projects(
        self,
        max_age_days: Optional[int] = None,
        dry_run: bool = False,
    ) -> List[GCResult]:
        """Sweep all projects for old segment files (cron job style).

        Args:
            max_age_days: Override max age for this sweep
            dry_run: If True, only report

        Returns:
            List of GCResult for each project processed
        """
        results = []
        effective_max_age = max_age_days or self.policy.max_age_days

        if not self.storage_root.exists():
            return results

        for project_dir in self.storage_root.iterdir():
            if not project_dir.is_dir() or not project_dir.name.isdigit():
                continue

            project_id = int(project_dir.name)
            original_max_age = self.policy.max_age_days
            self.policy.max_age_days = effective_max_age

            try:
                result = self.cleanup_project_segments(project_id, dry_run=dry_run)
                results.append(result)
            finally:
                self.policy.max_age_days = original_max_age

        return results


# Module-level convenience functions

def cleanup_after_export(
    project_id: int,
    keep_final: bool = True,
    pipeline_output_dir: Optional[str] = None,
    storage_root: Optional[str] = None,
    policy: Optional[GCRetentionPolicy] = None,
) -> Dict:
    """Convenience function to clean up segments after successful export.

    Args:
        project_id: Project ID that was exported
        keep_final: Keep final M4B/SRT/ZIP files
        pipeline_output_dir: Override pipeline output directory
        storage_root: Override storage root
        policy: Optional custom retention policy

    Returns:
        Dict with keys: deleted_files, freed_bytes, freed_mb, errors
    """
    if pipeline_output_dir is None:
        pipeline_output_dir = os.getenv("PIPELINE_OUTPUT_DIR", "./output")
    if storage_root is None:
        storage_root = os.getenv("STORAGE_ROOT", "./storage/books")

    manager = GCManager(
        pipeline_output_dir=pipeline_output_dir,
        storage_root=storage_root,
        policy=policy,
    )

    result = manager.cleanup_project_segments(project_id, keep_final=keep_final)

    return {
        "project_id": result.project_id,
        "deleted_files": result.deleted_files,
        "freed_bytes": result.freed_bytes,
        "freed_mb": result.freed_mb,
        "errors": result.errors,
        "policy": result.policy_applied,
    }


def gc_sweep_all(
    max_age_days: int = 30,
    pipeline_output_dir: Optional[str] = None,
    storage_root: Optional[str] = None,
    dry_run: bool = False,
) -> List[Dict]:
    """Convenience function for periodic GC sweep of all projects.

    Returns list of dict results for each project.
    """
    if pipeline_output_dir is None:
        pipeline_output_dir = os.getenv("PIPELINE_OUTPUT_DIR", "./output")
    if storage_root is None:
        storage_root = os.getenv("STORAGE_ROOT", "./storage/books")

    policy = GCRetentionPolicy(
        policy="clean_on_success",
        max_age_days=max_age_days,
    )

    manager = GCManager(
        pipeline_output_dir=pipeline_output_dir,
        storage_root=storage_root,
        policy=policy,
    )

    results = manager.sweep_all_projects(max_age_days=max_age_days, dry_run=dry_run)

    return [
        {
            "project_id": r.project_id,
            "deleted_files": r.deleted_files,
            "freed_bytes": r.freed_bytes,
            "freed_mb": r.freed_mb,
            "errors": r.errors,
            "policy": r.policy_applied,
        }
        for r in results
    ]


if __name__ == "__main__":  # pragma: no cover
    import sys

    logging.basicConfig(level=logging.INFO, format="%(levelname)s %(message)s")

    if len(sys.argv) < 2:
        print("Usage: python -m audiobook_studio.utils.gc_manager <command> [args]")
        print("Commands:")
        print("  cleanup <project_id> [--dry-run] [--no-keep-final]")
        print("  sweep [--max-age-days N] [--dry-run]")
        print("  config")
        sys.exit(1)

    cmd = sys.argv[1]

    if cmd == "cleanup":
        pid = int(sys.argv[2])
        dry = "--dry-run" in sys.argv
        keep_final = "--no-keep-final" not in sys.argv
        result = cleanup_after_export(pid, keep_final=keep_final)
        print(f"Deleted: {len(result['deleted_files'])} files")
        print(f"Freed: {result['freed_mb']:.2f} MB")
        if result["errors"]:
            print(f"Errors: {result['errors']}")

    elif cmd == "sweep":
        max_age = int(sys.argv[2]) if len(sys.argv) > 2 and sys.argv[2].isdigit() else 30
        dry = "--dry-run" in sys.argv
        results = gc_sweep_all(max_age_days=max_age, dry_run=dry)
        for r in results:
            print(f"Project {r['project_id']}: {len(r['deleted_files'])} files, {r['freed_mb']:.2f} MB")

    elif cmd == "config":
        print("GC Config:")
        print(f"  GC_POLICY={os.getenv('GC_POLICY', 'clean_on_success')}")
        print(f"  GC_KEEP_DAYS={os.getenv('GC_KEEP_DAYS', '7')}")
        print(f"  GC_KEEP_FINAL={os.getenv('GC_KEEP_FINAL', 'true')}")
        print(f"  GC_MAX_AGE_DAYS={os.getenv('GC_MAX_AGE_DAYS', '30')}")
        print(f"  PIPELINE_OUTPUT_DIR={os.getenv('PIPELINE_OUTPUT_DIR', './output')}")
        print(f"  STORAGE_ROOT={os.getenv('STORAGE_ROOT', './storage/books')}")