"""Initial Alembic migration – create core tables.

Generated manually to avoid requiring the ``alembic revision`` command.
"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "20241001_initial"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust as needed ###
    op.create_table(
        "books",
        sa.Column("id", sa.Integer(), primary_key=True, nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("author", sa.String(), nullable=False),
        sa.Column("language", sa.String(length=2), nullable=False),
        sa.Column("isbn", sa.String(), nullable=True),
    )
    op.create_table(
        "paragraphs",
        sa.Column("id", sa.Integer(), primary_key=True, nullable=False),
        sa.Column("book_id", sa.Integer(), nullable=False),
        sa.Column("index", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("speaker", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["book_id"],
            ["books.id"],
        ),
    )
    op.create_table(
        "tts_edits",
        sa.Column("id", sa.Integer(), primary_key=True, nullable=False),
        sa.Column("paragraph_id", sa.Integer(), nullable=False),
        sa.Column("edited_text", sa.Text(), nullable=False),
        sa.Column("voice", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["paragraph_id"],
            ["paragraphs.id"],
        ),
    )
    op.create_table(
        "routings",
        sa.Column("id", sa.Integer(), primary_key=True, nullable=False),
        sa.Column("paragraph_id", sa.Integer(), nullable=False),
        sa.Column("voice", sa.String(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["paragraph_id"],
            ["paragraphs.id"],
        ),
    )
    op.create_table(
        "qualities",
        sa.Column("id", sa.Integer(), primary_key=True, nullable=False),
        sa.Column("tts_edit_id", sa.Integer(), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("comments", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["tts_edit_id"],
            ["tts_edits.id"],
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust as needed ###
    op.drop_table("qualities")
    op.drop_table("routings")
    op.drop_table("tts_edits")
    op.drop_table("paragraphs")
    op.drop_table("books")
    # ### end Alembic commands ###
