"""add_composite_indexes_p2_5

Revision ID: 9edcfa5cce69
Revises: 84046aa425aa
Create Date: 2026-08-22 21:44:26.686667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '9edcfa5cce69'
down_revision: Union[str, None] = '84046aa425aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # First, update existing NULL segment_status to 'pending'
    op.execute("UPDATE chapters SET segment_status = 'pending' WHERE segment_status IS NULL")
    
    # Now we can safely alter the column to NOT NULL
    op.alter_column('chapters', 'segment_status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    
    # Create composite indexes (only new ones that don't exist yet)
    # Check if index exists before creating (SQLite doesn't support IF NOT EXISTS for CREATE INDEX)
    # We'll use a workaround with try/except or check via pragma
    
    conn = op.get_bind()
    
    # Helper to check if index exists
    def index_exists(index_name: str) -> bool:
        result = conn.execute(
            sa.text("SELECT 1 FROM sqlite_master WHERE type='index' AND name=:name"),
            {"name": index_name}
        )
        return result.fetchone() is not None
    
    # Chapter composite indexes
    if not index_exists('ix_chapters_project_id_index'):
        op.create_index('ix_chapters_project_id_index', 'chapters', ['project_id', 'index'], unique=False)
    if not index_exists('ix_chapters_project_id_status_index'):
        op.create_index('ix_chapters_project_id_status_index', 'chapters', ['project_id', 'status', 'index'], unique=False)
    
    # Paragraph composite indexes
    if not index_exists('ix_paragraphs_chapter_id_index'):
        op.create_index('ix_paragraphs_chapter_id_index', 'paragraphs', ['chapter_id', 'index'], unique=False)
    if not index_exists('ix_paragraphs_chapter_id_status'):
        op.create_index('ix_paragraphs_chapter_id_status', 'paragraphs', ['chapter_id', 'status'], unique=False)
    if not index_exists('ix_paragraphs_project_id_status_index'):
        op.create_index('ix_paragraphs_project_id_status_index', 'paragraphs', ['project_id', 'status', 'index'], unique=False)
    
    # AudioSegment composite indexes
    if not index_exists('ix_audio_segments_chapter_id_index'):
        op.create_index('ix_audio_segments_chapter_id_index', 'audio_segments', ['chapter_id', 'index'], unique=False)
    if not index_exists('ix_audio_segments_project_id_status'):
        op.create_index('ix_audio_segments_project_id_status', 'audio_segments', ['project_id', 'status'], unique=False)
    if not index_exists('ix_audio_segments_project_chapter_current'):
        op.create_index('ix_audio_segments_project_chapter_current', 'audio_segments', ['project_id', 'chapter_id', 'is_current'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_audio_segments_project_chapter_current', table_name='audio_segments')
    op.drop_index('ix_audio_segments_project_id_status', table_name='audio_segments')
    op.drop_index('ix_audio_segments_chapter_id_index', table_name='audio_segments')
    
    op.drop_index('ix_paragraphs_project_id_status_index', table_name='paragraphs')
    op.drop_index('ix_paragraphs_chapter_id_status', table_name='paragraphs')
    op.drop_index('ix_paragraphs_chapter_id_index', table_name='paragraphs')
    
    op.drop_index('ix_chapters_project_id_status_index', table_name='chapters')
    op.drop_index('ix_chapters_project_id_index', table_name='chapters')
    
    op.alter_column('chapters', 'segment_status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###
