"""Alembic environment configuration.

This file sets up the Alembic context to use the project's SQLAlchemy
metadata (the ``Base`` object) and the database URL from the environment.
It is based on the standard template generated by ``alembic init`` but
adjusted for the project's package layout.
"""

import os
import sys
from logging.config import fileConfig

from sqlalchemy import engine_from_config, pool

# Ensure the project package is on the import path
PROJECT_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
if PROJECT_ROOT not in sys.path:
    sys.path.append(PROJECT_ROOT)

# this is the Alembic Config object, which provides
# access to the values within the .ini file in use.
from alembic import context

# Import the Base metadata from the project
from src.audiobook_studio.database import DATABASE_URL, Base  # noqa: E402

config = context.config

# Interpret the config file for Python logging.
# This line sets up loggers basically.
if config.config_file_name is not None:
    fileConfig(config.config_file_name)

# Set the sqlalchemy.url programmatically, allowing the env var to win.
config.set_main_option("sqlalchemy.url", os.getenv("DATABASE_URL", DATABASE_URL))

# add your model's MetaData object here for 'autogenerate' support
target_metadata = Base.metadata


def run_migrations_offline() -> None:
    """Run migrations in 'offline' mode.

    This configures the context with just a URL and not an Engine, which
    allows the generation of pure SQL scripts.
    """
    url = config.get_main_option("sqlalchemy.url")
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
    )

    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    """Run migrations in 'online' mode.

    In this scenario we create an Engine and associate a connection with the
    context.
    """
    connectable = engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )

    with connectable.connect() as connection:
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
            compare_type=True,
        )

        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
